version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: ddd-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - ddd-network
    restart: always

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: ddd-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - ddd-network

  kafka:
  image: confluentinc/cp-kafka:7.3.0
  container_name: ddd-kafka
  depends_on:
    - zookeeper
  ports:
    - "9092:9092"
  environment:
    KAFKA_HEAP_OPTS: "-Xmx256M -Xms128M"
    KAFKA_BROKER_ID: 1
    KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
    KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
    KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  networks:
    - ddd-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ddd-api-service
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
      - kafka
    env_file:
      - .env
    environment:
      - PORT=8000
      - MONGODB_URI=mongodb://mongodb:27017/ddd_task
      - KAFKA_BROKERS=kafka:29092
      - KAFKA_CLIENT_ID=post-service
      - KAFKA_GROUP_ID=post-group
      - NODE_ENV=production
    networks:
      - ddd-network
    restart: on-failure

volumes:
  mongo-data:

networks:
  ddd-network:
    driver: bridge
